[workspace.package]
edition = "2024"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]

[workspace]
resolver = "3"

members = [
  "ww_gpio",
  "ww_dfu",
]

[workspace.dependencies]
wire_weaver = { path = "../wire_weaver/wire_weaver", default-features = false }