[package]
name = "ww_gpio"
version = "0.1.0"
edition.workspace = true
description = "GPIO control data types and remote bridging API"
license.workspace = true
repository.workspace = true

[dependencies]
wire_weaver = { workspace = true }
